### PR TITLE
audio_hal_interface: Optionally use sysbta HAL

### PR DESCRIPTION
**Pull request by RT1648**

### CODE REVIEW

**Comment by TheHardGamer** [comment]
Why are you pushing a separate patch file in the commit? where is the commit authorship?

**Comment by RT1648** [comment]
> Why are you pushing a separate patch file in the commit? where is the commit authorship?

It's not a patch file. Please check it

**Comment by TheHardGamer** [comment]
> > Why are you pushing a separate patch file in the commit? where is the commit authorship?
> 
> It's not a patch file. Please check it

0001-audio_hal_interface-Optionally-use-sysbta-HAL.patch ??

**Comment by RT1648** [comment]
> > > Why are you pushing a separate patch file in the commit? where is the commit authorship?
> > 
> > 
> > It's not a patch file. Please check it
> 
> 0001-audio_hal_interface-Optionally-use-sysbta-HAL.patch ??

Oh it was by mistake. Please ignore it. It just become the part of commit but it's not in the repo

**Comment by TheHardGamer** [comment]
> > > > Why are you pushing a separate patch file in the commit? where is the commit authorship?
> > > 
> > > 
> > > It's not a patch file. Please check it
> > 
> > 
> > 0001-audio_hal_interface-Optionally-use-sysbta-HAL.patch ??
> 
> Oh it was by mistake. Please ignore it. It just become the part of commit but it's not in the repo

So won't it be added to the repo if I merge this PR?

**Comment by RT1648** [comment]
> > > > > Why are you pushing a separate patch file in the commit? where is the commit authorship?
> > > > 
> > > > 
> > > > It's not a patch file. Please check it
> > > 
> > > 
> > > 0001-audio_hal_interface-Optionally-use-sysbta-HAL.patch ??
> > 
> > 
> > Oh it was by mistake. Please ignore it. It just become the part of commit but it's not in the repo
> 
> So won't it be added to the repo if I merge this PR?

Nope, it won't be added

**Comment by RT1648** [comment]
> > > > > Why are you pushing a separate patch file in the commit? where is the commit authorship?
> > > > 
> > > > 
> > > > It's not a patch file. Please check it
> > > 
> > > 
> > > 0001-audio_hal_interface-Optionally-use-sysbta-HAL.patch ??
> > 
> > 
> > Oh it was by mistake. Please ignore it. It just become the part of commit but it's not in the repo
> 
> So won't it be added to the repo if I merge this PR?

If u want I'll do a new PR

**Comment by TheHardGamer** [comment]
Closing since you lack basic git knowledge, please create a proper pull request with intact authorship and without any unnecessary files.

**Pull request closed without merging**
